name: macOS

on: [push]

jobs:
  build_package:
    name: Build and sign macOS Installer package
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          DEV_ID: ${{ secrets.DEV_ID }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output=$CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

      #     # Create notabot config file
      #     echo -e "[developer]\nidentity = $DEV_ID"  > notabot.cfg
      #     echo -e "username = $DEV_USERNAME"  >> notabot.cfg
      #     echo -e "password = $DEV_PASSWORD\n"  >> notabot.cfg
      #     echo -e "[entitlements]\nplist_file = entitlements.plist"  >> notabot.cfg
      #     echo -e "[paths]\nbundle_path = dist/SnapPy.app" >> notabot.cfg
      #     echo -e "dmg_path = disk_images/SnapPy.dmg" >> notabot.cfg
      #     cp notabot.cfg snappy/macOS_app

      # - name: Run build script
      #   run: |
      #     # Uses PyPI for auxiliary SnapPy packages (FXrays, Cython, etc.)
      #     bash build_mac_app.sh --use-pypi

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: SnapPy.dmg
      #     path: snappy/macOS_app/disk_images/SnapPy.dmg
